version: '3'

services:
  app:
    build: ./tests/app
    ports:
      - "8082:8082"
# -----------------------------------------------------
  nginx-gateway: 
    image: vahidmostofi/nginx-gateway:latest
    build: ./nginx-gateway
    ports:
      - "8111:9090"
    environment:
      - TELEGRAF_SYSLOG_SERVER=telegraf-agent:6514
      - PORT=9090
      - PROXY_PASS_URL=http://app:8082
    depends_on:
      - telegraf-agent
# -----------------------------------------------------
  telegraf-agent:
    image: vahidmostofi/telegraf-agent:latest
    build: ./telegraf-agent
    ports:
      - "8125:8125"
      - "8092:8092"
      - "8094:8094"
      - "6514:6514"
    environment:
      - INFLUXDB_URL=
      - INFLUXDB_TOKEN=
      - INFLUXDB_ORG=
      - INFLUXDB_BUCKET=
      - NGINX_DEFAULT_STATS_URL=http://nginx-gateway:9090/nginx_status
      - SYSLOG_SERVER_PORT=6514