apiVersion: apps/v1
kind: Deployment
metadata:
  name: endpoints-monitor
spec:
  selector:
    matchLabels:
      app: endpoints-monitor
  replicas: 1
  template:
    metadata:
      labels:
        app: endpoints-monitor
    spec:
      containers:
        - name: nginx
          image: vahidmostofi/nginx-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9099
          env:
            - name: TELEGRAF_SYSLOG_SERVER
              value: "localhost:6514"
            - name: PORT
              value: "9099"
            - name: PROXY_PASS_URL
              value: http://gateway:9080
          resources:
            requests:
              memory: "512Mi"
              cpu: 1.0
            limits:
              memory: "512Mi"
              cpu: 1.0
        - name: telegraf-agent
          image: vahidmostofi/telegraf-agent:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8125
            - containerPort: 8092
            - containerPort: 8094
            - containerPort: 6514
          env:
            - name: INFLUXDB_URL
              value: "http://136.159.209.214:8086"
            - name: INFLUXDB_TOKEN
              value: "XoiQEGsvrh2YstBGhOWWC0UOL4c-b8GYtpo5xY_3LcLRA_mha2xex0AFiDOT-I39GW27rDc1JuEPNMwIEzmBqg=="
            - name: INFLUXDB_ORG
              value: "uofc"
            - name: INFLUXDB_BUCKET
              value: "general"
            - name: NGINX_DEFAULT_STATS_URL
              value: "http://localhost:9099/nginx_status"
            - name: SYSLOG_SERVER_PORT
              value: "6514"
          resources:
            requests:
              memory: "512Mi"
              cpu: 1.0
            limits:
              memory: "512Mi"
              cpu: 1.0

---
apiVersion: v1
kind: Service
metadata:
  name: endpoints-monitor
spec:
  selector:
    app: endpoints-monitor
  ports:
    - port: 9099
      targetPort: 9099
  type: LoadBalancer
